name: ci

on:
  - push
  - pull_request

env:
  # maven.wagon.rto is in millis, defaults to 30m
  MAVEN_OPTS: "-Xmx512M -XX:+ExitOnOutOfMemoryError -Dmaven.wagon.rto=60000"
  MAVEN_INSTALL_OPTS: "-Xmx2G -XX:+ExitOnOutOfMemoryError -Dmaven.wagon.rto=60000"
  MAVEN_FAST_INSTALL: "-B -V --quiet -T C1 -DskipTests -Dair.check.skip-all"

jobs:
  maven-checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 11
          - 14
    steps:
      - name: Free Disk Space
        run: |
          df -h
          sudo apt-get clean
          df -h
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Maven Checks
        run: |
          export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
          ./bin/retry ./mvnw install -B -V -T C1 -DskipTests -P ci -pl '!presto-server-rpm'
      - name: Test Server RPM
        run: |
          export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
          ./bin/retry ./mvnw verify -B -P ci -pl presto-server-rpm
      - name: Clean Maven Output
        run: ./mvnw clean -pl '!presto-server,!presto-cli'
      - name: Test Docker Image
        run: docker/build-local.sh

  error-prone-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Install
        run: |
          export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
          ./bin/retry ./mvnw install ${MAVEN_FAST_INSTALL} -pl '!presto-docs,!presto-server,!presto-server-rpm'
      - name: Error Prone Checks
        run: |
          export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
          ./mvnw -B -T C1 clean test-compile -Dair.check.skip-all -P errorprone-compiler-presto \
            -pl '!presto-docs,!presto-server,!presto-server-rpm'

  web-ui-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Web UI Checks
        run: presto-main/bin/check_webui.sh

  hive-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - config-empty
          - config-hdp3
          # TODO: config-cdh5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install Hive Module
        run: |
          export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
          ./bin/retry ./mvnw install ${MAVEN_FAST_INSTALL} -am -pl presto-hive-hadoop2
      - name: Run Hive Tests
        run: |
          source presto-product-tests/conf/product-tests-${{ matrix.config }}.sh &&
            presto-hive-hadoop2/bin/run_hive_tests.sh
      - name: Run Hive S3 Tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AwsAccessKey }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AwsSecretKey }}
          S3_BUCKET: "presto-ci-test"
          S3_BUCKET_ENDPOINT: "s3.us-east-2.amazonaws.com"
        run: |
          if [ "${AWS_ACCESS_KEY_ID}" != "" ]; then
            source presto-product-tests/conf/product-tests-${{ matrix.config }}.sh &&
              presto-hive-hadoop2/bin/run_hive_s3_tests.sh
          fi
      - name: Run Hive Glue Tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AwsAccessKey }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AwsSecretKey }}
          AWS_REGION: us-east-2
        run: |
          if [ "${AWS_ACCESS_KEY_ID}" != "" ]; then
            ./mvnw test -B -Dair.check.skip-all -pl presto-hive -P test-hive-glue
          fi
      - name: Run Hive Alluxio Tests
        run: |
          source presto-product-tests/conf/product-tests-${{ matrix.config }}.sh &&
            presto-hive-hadoop2/bin/run_hive_alluxio_tests.sh

  test-other-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Install
        run: |
          export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
          ./bin/retry ./mvnw install ${MAVEN_FAST_INSTALL} -pl '!presto-docs,!presto-server,!presto-server-rpm'
      - name: Maven Tests
        run: |
          ./mvnw test -B -fae -Dair.check.skip-all -pl '
            !presto-main,
            !presto-tests,
            !presto-raptor-legacy,
            !presto-accumulo,
            !presto-cassandra,
            !presto-hive,!presto-orc,!presto-parquet,
            !presto-mongodb,!presto-kafka,!presto-elasticsearch,
            !presto-redis,
            !presto-sqlserver,!presto-postgresql,!presto-mysql,
            !presto-oracle,
            !presto-kudu,
            !presto-phoenix,!presto-iceberg,!presto-druid,
            !presto-docs,!presto-server,!presto-server-rpm'

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        modules:
          - "presto-main"
          - "presto-tests"
          - "presto-tests -P ci-only"
          - "presto-raptor-legacy"
          - "presto-accumulo"
          - "presto-cassandra"
          - "presto-hive,presto-orc"
          - "presto-hive,presto-parquet -P test-parquet"
          - "presto-mongodb,presto-kafka,presto-elasticsearch"
          - "presto-redis"
          - "presto-sqlserver,presto-postgresql,presto-mysql"
          - "presto-oracle"
          - "presto-kudu"
          - "presto-phoenix,presto-iceberg,presto-druid"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Install
        run: |
          export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
          ./bin/retry ./mvnw install ${MAVEN_FAST_INSTALL} -am -pl $(echo '${{ matrix.modules }}' | cut -d' ' -f1)
      - name: Maven Tests
        run: ./mvnw test -B -fae -Dair.check.skip-all -pl ${{ matrix.modules }}

  pt:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - config-empty
          - config-hdp3
          - config-cdh5
        suite:
          - suite-1
          - suite-2
          - suite-3
          # suite-4 does not exist
          - suite-5
          - suite-6-non-generic
          - suite-7-non-generic
          - suite-8-non-generic
        exclude:
          - config: config-hdp3
            suite: suite-6-non-generic
          - config: config-hdp3
            suite: suite-7-non-generic
          - config: config-hdp3
            suite: suite-8-non-generic
          - config: config-cdh5
            suite: suite-6-non-generic
          - config: config-cdh5
            suite: suite-7-non-generic
          - config: config-cdh5
            suite: suite-8-non-generic
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Install
        run: |
          export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
          ./bin/retry ./mvnw install ${MAVEN_FAST_INSTALL} -pl '!presto-docs,!presto-server-rpm'
      - name: Free Disk Space
        run: |
          docker image prune -af
          sudo apt-get clean
          rm -rf ~/.m2/repository
      - name: Product Tests
        run: |
          export PTL_BIND_PORTS=false &&
          source presto-product-tests/conf/product-tests-${{ matrix.config }}.sh &&
            presto-product-tests/bin/product-tests-${{ matrix.suite }}.sh
